# vich_uploader:
    # db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
# vich_uploader:
#     db_driver: orm # ou 'mongodb' ou 'propel'
#     mappings:
#         audio_files:
#             uri_prefix: /upload/audio/coran
#             upload_destination: '%kernel.project_dir%/public/upload/audio/coran'
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#             delete_on_update: true
#             delete_on_remove: true
vich_uploader:
    db_driver: orm
    mappings:
        audio_file:
            uri_prefix: /upload/audio/coran/
            upload_destination: '%kernel.project_dir%/public/upload/audio/coran/'
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        audio_file_adan:
            uri_prefix: /upload/audio/adan/
            upload_destination: '%kernel.project_dir%/public/upload/audio/coran/'
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
# config/packages/vich_uploader.yaml
# vich_uploader:
#     db_driver: orm
#     mappings:
#         qran_audio:
#             uri_prefix: /uploads/audios  # Dossier public où les fichiers seront accessibles
#             upload_destination: '%kernel.project_dir%/public/uploads/audios'  # Dossier de stockage des fichiers
#             allowed_mime_types: ['audio/mpeg', 'audio/wav']  # Types MIME autorisés
#             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#             inject_on_load: true
#             delete_on_update: true
#             delete_on_remove: true
